### ISSUE TITLE
Merge mysql wordpress deployment files

### ISSUE THREAD

**Issue by cloud-pharaoh** [GoogleCloudPlatform/kubernetes-engine-samples#102]
Deployment files:
- https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/cloudsql/mysql_wordpress_deployment.yaml
- https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/wordpress-persistent-disks/wordpress_cloudsql.yaml.template

The above 2 files are almost identical except for the fact that the latter is linked to this [tutorial](https://cloud.google.com/kubernetes-engine/docs/tutorials/persistent-disk) and uses persistent disks. 
Some consideration needs to happen to assess how to best merge these or keep only one of them somehow to avoid this duplication.

**Comment by kurtisvg** [comment]
Please see #96 for more context.
