### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by shikha130vv** [GoogleCloudPlatform/kubernetes-engine-samples#108]
in url (https://cloud.google.com/kubernetes-engine/docs/how-to/exposing-apps), the name of the pods are incorrect and lead to confusion.
Here is a manifest for a Deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: metrics
      department: sales
  replicas: 3
  template:
    metadata:
      labels:
        app: metrics
        department: sales
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
Copy the manifest to a file named my-deployment.yaml, and create the Deployment:

kubectl apply -f my-deployment.yaml
Verify that three Pods are running:

kubectl get pods
The output shows three running Pods:

NAME                              READY     STATUS    RESTARTS   AGE
service-how-to-76699757f9-h4xk4   1/1       Running   0          4s
service-how-to-76699757f9-tjcfq   1/1       Running   0          4s
service-how-to-76699757f9-wt9d8   1/1       Running   0    

In

**Comment by askmeegs** [comment]
Hello, thank you for raising this issue. The Exposing Apps doc is now updated to reflect the correct `my-deployment` name: https://cloud.google.com/kubernetes-engine/docs/how-to/exposing-apps

I'm going to close this issue. Thanks!
