### ISSUE TITLE
sd_dummy_exporter.go has error "Failed to write time series data"

### ISSUE THREAD

**Issue by CatherineF-dev** [GoogleCloudPlatform/kubernetes-engine-samples#1084]
`
2024/01/04 20:04:11 Failed to write time series data for new resource model: googleapi: Error 500: Internal error encountered. Please retry after a few seconds. If internal errors persist, contact support at https://cloud.google.com/support/docs., backendError
`

**Comment by bourgeoisor** [comment]
Hi @CatherineF-dev! Could you provide some more details / context? What commands did you run? Is this issue reproducible? Etc.

**Comment by CatherineF-dev** [comment]
This issue is fixed after I rebuild custom-metrics-stackdriver-adapter from master branch.

Before had this error when following https://cloud.google.com/kubernetes-engine/docs/tutorials/autoscaling-metrics#step1

**Comment by bourgeoisor** [comment]
So I can close this issue as fixed?
