### ISSUE TITLE
dev shm size option works in google kubernetes engine 1.12 but doesn't work on higher versions

### ISSUE THREAD

**Issue by shanmukha511** [GoogleCloudPlatform/kubernetes-engine-samples#114]
Sample Deployment File:
apiVersion: v1
kind: Pod
metadata:
  name: myvolumes-pod1
spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: myvolumes-container-1
    
    command: ['sh', '-c', 'echo The Bench Container 1 is Running ; sleep 3600']
    
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm

  - image: alpine
    imagePullPolicy: IfNotPresent
    name: myvolumes-container-2
    
    command: ['sh', '-c', 'echo The Bench Container 2 is Running ; sleep 3600']
    
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm

  - image: alpine
    imagePullPolicy: IfNotPresent
    name: myvolumes-container-3
    
    command: ['sh', '-c', 'echo The Bench Container 3 is Running ; sleep 3600']
    
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm

  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "1024Mi"

Need to increase /dev mount point  size along with /dev/shm size.

**Comment by askmeegs** [comment]
Hello! Thank you for filing this issue.
Does this issue reference any specific [GKE docs](https://cloud.google.com/kubernetes-engine/docs) or samples in this repository, so that we can update accordingly? Thank you!

**Comment by askmeegs** [comment]
I'm going to close this issue because I am unable to find relevant samples in this repo that use `/dev/mount` or `/dev/shm`. Feel free to reopen with followups, thanks!

**Comment by shanmukha511** [comment]
Hi @askmeegs 
This is concept of volume emtydir() and /dev/shm which we are mouting the volume to that mount point /dev/shm and which internally creates some temporary memory which our application uses for some purpose.Now question is that manifest when we execute on gke 1.12 and gke 1.13 or 1.14
it behaving different. 
This was output of gke  1.14.10-gke.36 see the /dev/shm size and /dev size is 64M we want to increase /dev size but its coming default 64M.
root@test-0:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          95G  3.2G   92G   4% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/sda1        95G  3.2G   92G   4% /etc/hosts
/dev/sdb        2.9G  9.0M  2.9G   1% /dev/shm
tmpfs           3.7G   12K  3.7G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           3.7G     0  3.7G   0% /proc/acpi
tmpfs           3.7G     0  3.7G   0% /proc/scsi
tmpfs           3.7G     0  3.7G   0% /sys/firmware

And when we execute same manifest on gke 1.12.Below output you get

root@test-0:/# df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay         489G   68G  421G  14% /
tmpfs            52G     0   52G   0% /dev
tmpfs            52G     0   52G   0% /sys/fs/cgroup
/dev/sda1       489G   68G  421G  14% /etc/hosts
/dev/sdb        2.9G  9.0M  2.9G   1% /dev/shm
tmpfs            52G   12K   52G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            52G     0   52G   0% /sys/firmware

Now question is when we deploy the same manifest but different gke versions the /dev size is varying. we want to acheive the same what we acheived using 1.12 gke i.e the /dev size to be increased not defaut of 64M.

**Comment by shanmukha511** [comment]
@askmeegs 
To get more info on this issue.
Can you please deploy the below manifest on gke 1.12 and 1.14 and execute command df-h inside pod and compare the /dev size and you can find the difference.

**Manifest File:**

apiVersion: v1
kind: Service
metadata:
   name: test
   labels:
      service: test
spec:
   type: ClusterIP
   clusterIP: None
   selector:
      service: test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: test
   labels:
      service: test
spec:
   serviceName: test
   replicas: 1
   updateStrategy:
      type: RollingUpdate
   selector:
      matchLabels:
         service: test
   template:
      metadata:
         labels:
            service: test
      spec:
         terminationGracePeriodSeconds: 40
         containers:
            - name: test
              image: nginx
              imagePullPolicy: Always
              volumeMounts:
                 - name: testshm
                   mountPath: /dev/shm
         volumes:
            - name: testshm
              emptyDir:
                 medium: Memory
   volumeClaimTemplates:
      - metadata:
           name: testshm
        spec:
           accessModes:
              - ReadWriteOnce
           resources:
              requests:
                 storage: 3Gi
