### ISSUE TITLE
Any way to download plaintext logs?

### ISSUE THREAD

**Issue by zcain117** [GoogleCloudPlatform/kubernetes-engine-samples#115]
We are running a suite of tests on GKE. We are using the default logging location (Stackdriver).

I want to get only the text payloads from my logs, e.g. the output of this command:
`gcloud logging read 'resource.type=k8s_container resource.labels.project_id=xl-ml-test resource.labels.location=us-central1-b resource.labels.cluster_name=xl-ml-test resource.labels.namespace_name=automated resource.labels.pod_name:pt-nightly-resnet50-convergence-v3-8-manual-gd258 timestamp>="2020-01-01T00:00:00Z"' --limit 10000000000000 --order asc --format "value(textPayload)" > log.txt && sed -i '/^$/d' log.txt`

I can generate URLs to see those same logs in Stackdriver Logging UI but there's no way to download them.

How would you recommend we structure our GKE logging to make it easier to access plaintext logs from our containers?

**Comment by askmeegs** [comment]
@simonz130 do you know if there's a recommended way to do this with Cloud Logging? (Download plaintext logs from structured GKE logs?)

**Comment by simonz130** [comment]
Something like this: (it stores the output in text file - then do what you want with it)

```bash
gcloud logging read 'resource.type=container resource.labels.cluster_name=GKE-CLUSTER logName=deployment_you_want_logs_from timestamp>="2020-07-29T00:00:00Z"' --limit 100 --order asc --format "value(textPayload)" > my-text-file.log
```
