### ISSUE TITLE
GKE Cluster hangs

### ISSUE THREAD

**Issue by limbuu** [GoogleCloudPlatform/kubernetes-engine-samples#119]
This is very weird since we have been using kubernetes for very long time we had never encountered this issue before hand. Today, as i was making multiple node pools and downgrade one default node pool so that all the application pods transfer to new node pool. Sadly, i configured small disk size which gave pressure to the VM when i try to schedule new pod to it. and the cluster starts to hang as the default pool starts to autoscale itself in loop, throws unknown error at a time and continuously doing this again and again. Can some one from the gke developers help me on this???

**Comment by limbuu** [comment]
If i try to do other things in the cluster its says Operation operation-1586864553560-6db5eb90 is currently operating on cluster

**Comment by newworld0000** [comment]
Try to cancel this operation
gcloud beta container operations cancel    operation-1586864553560-6db5eb90    --zone us-central1-c

**Comment by wofr** [comment]
I do have an operations which hangs sind 1 month
 `NAME                                                          TYPE            LOCATION        TARGET            STATUS_MESSAGE  STATUS   START_TIME                      END_TIME
operation-1690195702232-2db62bae-d4c9-40ef-9156-f495f41be875  UPDATE_CLUSTER  europe-west4-a  xxxxx-np                  RUNNING  2023-07-24T10:48:22.232284692Z`

and I find no way to cancel it.  GKE tries to update a node-pool which does not exist anymore.   So far I've not found a solution to remove the cluster.
