### ISSUE TITLE
Support gRPC

### ISSUE THREAD

**Issue by rramkumar1** [GoogleCloudPlatform/kubernetes-engine-samples#135]
We should add gRPC support to the whereami binary (including support for the standard gRPC health check API)

**Comment by rramkumar1** [comment]
@theemadnes

**Comment by theemadnes** [comment]
good idea @rramkumar1 - i'll start planning this out

**Comment by theemadnes** [comment]
@rramkumar1 re: health check API are you referring to [this](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)?

**Comment by rramkumar1** [comment]
@theemadnes yep

**Comment by theemadnes** [comment]
@rramkumar1 in case you were still interested this is almost ready to go. code works - i just need to write docs and do PR. [take a look here](https://github.com/theemadnes/kubernetes-engine-samples/blob/grpc_support/whereami/app.py) if you're interested. also the deployment spec reflects use of healthcheck API.

**Comment by theemadnes** [comment]
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/150

**Comment by theemadnes** [comment]
PR merged
