### ISSUE TITLE
Add jq, tcpdump, and iputils to whereami container image

### ISSUE THREAD

**Issue by mark-church** [GoogleCloudPlatform/kubernetes-engine-samples#137]
Taking https://github.com/nicolaka/netshoot as an example, this container has a bunch of networking tools built into the image. While I don't think we need all of these I do think that jq, tcpdump, and iputils (for ping) would be very helpful.

I realized this when I wanted to do the following from one whereami pod to another whereami pod:

```
kubectl exec -it foo-5cc954d898-7q7r5 -- sh

$ curl foo-svc:80 | jq '.pod_name'
sh: 1: jq: not found
```

@theemadnes @nicolaka

**Comment by theemadnes** [comment]
Let's chat about this further. Thinking about the Unix philosophy of "do one thing and do it well". `whereami`'s one thing is location reporting/diagnostics for K8s pods. `netshoot`'s one thing is K8s network troubleshooting. I'm thinking we should leverage `netshoot` for its superpower of aggregating a bunch of useful tools instead of trying to replicate it.

**Comment by mark-church** [comment]
@theemadnes I'd like to open this issue back up. I want to use whereami in the Cloud DNS docs (https://cloud.devsite.corp.google.com/kubernetes-engine/docs/how-to/cloud-dns) but I can't because it has no local networking troubleshooting tools. I think the original request was misunderstood because the purpose was not to use whereami as a troubleshooting container, but rather it should have the minimum amount of tools to demonstrate different networking things.



```
kubectl exec -it whereami -- sh
$
$
$ dig
sh: 3: dig: not found
$ drill
sh: 4: drill: not found
$ nslookup
sh: 5: nslookup: not found
$ exit
```

The following tools would be useful to have:
- dig or drill
- ping
- git
- openssl (although I could live without it)
- jq 
- iputils (I think this is for the "ip" command)

**Comment by theemadnes** [comment]
ok that makes sense. can you set up a little time to chat about it? want to figure out if we make it default or add a companion "whereami + utils" image, and also walk through figuring out if we need to modify any permissions needed for the pod.

**Comment by theemadnes** [comment]
switching this to just include `curl` per request by @mark-church

**Comment by theemadnes** [comment]
I checked with @mark-church and we can close this
