### ISSUE TITLE
GKE nodes restarting due to soft lockup -  CPU

### ISSUE THREAD

**Issue by yogeshbidari** [GoogleCloudPlatform/kubernetes-engine-samples#138]
Nodes on the GKE cluster are restarting with error `watchdog: BUG: soft lockup - CPU#2 stuck for XXs`.

The above error will trigger the kernel panic `Kernel panic - not syncing: softlockup: hung tasks` and then the node reboots after 10sec.

GKE version: v1.14.10-gke.37

**Comment by askmeegs** [comment]
Hello, I was unfortunately not able to reproduce this issue. 

After searching for similar issues, it seems like this is not a GKE-specific issue, but rather an open source Kubernetes problem that happens occasionally -- 
- Kubernetes -https://github.com/kubernetes/kubernetes/issues/37853 
- Openshift: https://bugzilla.redhat.com/show_bug.cgi?id=1579498
