### ISSUE TITLE
frontend service: Error syncing load balancer

### ISSUE THREAD

**Issue by leilajal** [GoogleCloudPlatform/kubernetes-engine-samples#143]
I am running guestbook example on a Google Container Engine installation ([tutorial](https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook))
In creating frontend service, I got an error:
Error syncing load balancer: failed to ensure load balancer (failed to create forwarding rule for load balancer)

```

NAME       TYPE                CLUSTER-IP      EXTERNAL-IP            PORT(S)        AGE
frontend   LoadBalancer   X.X.X.X              <pending>           80:31463/TCP.     11m

```

External IP is pending.

Error in Kubernetes Engine > Services:

`Error syncing load balancer: failed to ensure load balancer: failed to create forwarding rule for load balancer (a5ec51ef24a914395ac55474dbf1a76b(default/frontend)): googleapi: Error 412: Constraint constraints/compute.restrictLoadBalancerCreationForTypes violated for projects/test-03-10-05-2020. Forwarding Rule projects/test-03-10-05-2020/regions/us-east1/forwardingRules/a5ec51ef24a914395ac55474dbf1a76b of type EXTERNAL_NETWORK_TCP_UDP is not allowed., conditionNotMet`

**Comment by askmeegs** [comment]
Hello,

It looks like the project you're running this sample in has Organizational Constraints for Cloud Load Balancing. The guestbook example tries to expose a service type=LoadBalancer and it seems like your project doesn't allow public-facing IPs. 
https://cloud.google.com/load-balancing/docs/org-policy-constraints

I recommend trying this example on a project in a different org, or in a project that allows external load balancers.
