### ISSUE TITLE
hello-app example fails on Apple M1 machine

### ISSUE THREAD

**Issue by ericdrosas87** [GoogleCloudPlatform/kubernetes-engine-samples#179]
The image golang:1.8-alpine did not build on my M1 Macbook. There was an error in the terminal about Docker being unable to find the metadata for this image.

Instead, I had to use: golang:alpine3.13

This led me to making the following changes to the Dockerfile:

```
#FROM golang:1.8-alpine
FROM golang:alpine3.13
ADD . /go/src/hello-app
WORKDIR /go/src/hello-app
RUN go mod init
RUN go mod tidy
RUN go install hello-app

FROM alpine:latest
COPY --from=0 /go/bin/hello-app .
ENV PORT 8080
CMD ["./hello-app"]
```

This built fine, but when it came time to deploy this image to the GKE cluster (which succeeded) the pods were stuck in a status of "CrashLoopBackOff".

The only line in the pod log was:

`
standard_init_linux.go:211: exec user process caused "exec format error"
`

...which I learned through some Googling happens when you build on one architecture and deploy to another.

I had to build using buildx in order to get the deployment up and running successfully:

`
docker buildx build --platform linux/amd64 -t <image name> .
`

I suggest modifying the associated tutorials to offer this alternative route to deployment for M1 machines.

**Comment by askmeegs** [comment]
Moving this to a P3 given ongoing discussions for docker build instructions for M1 machines, across GCP samples and docs.

**Comment by ckim328** [comment]
cooling off for OSLO and providing an update, this sample repo still only supports AMD machines

**Comment by minherz** [comment]
GKE [supports][1] ARM architecture which should resolve the problem with images built on Mac. However, the _default_ provisioning of GKE cluster should be altered to deploy to the node pool that is provisioned with ARM nodes.

[1]:  https://cloud.google.com/blog/products/containers-kubernetes/gke-supports-new-arm-based-tau-t2a-vms
