### ISSUE TITLE
Use "main" instead of "master"

### ISSUE THREAD

**Issue by NimJay** [GoogleCloudPlatform/kubernetes-engine-samples#198]
The use of `master` (as our default branch) isn't very _Googly_. Let's use `main` instead.
Some things to consider:
* We will need to update all the Terraform for the Google Cloud Build Triggers that are responsible for rebuilding/repushing Docker images. Namely, we need to update [`/terraform/google-cloud-build-triggers.tf`](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/35b4e0f37d6ac8e691f09bd2ef7476aab6dc9232/terraform/google-cloud-build-triggers.tf). 
* How will this affect GCP tutorials that reference snippets directly from this repository?

**Comment by ckim328** [comment]
This has already been completed. Closing issue
