### ISSUE TITLE
Add OpenTelemetry tracing to Whereami for Flask mode

### ISSUE THREAD

**Issue by theemadnes** [GoogleCloudPlatform/kubernetes-engine-samples#217]
detect if running on GKE, and if so, push traces to Cloud Tracing

**Comment by theemadnes** [comment]
using OpenCensus for this instead of OT due to some pip dependency stuff i don't have time to fix yet, and only solving for Flask for now. Will do gRPC in another issue.

**Comment by askmeegs** [comment]
Hi Alex! We instrumented the Bank of Anthos python Flask services with OpenTelemetry. This may help! 
https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/src/frontend/frontend.py#L564

**Comment by theemadnes** [comment]
nice - the instrumentation looks almost identical to what i added.

**Comment by theemadnes** [comment]
done
