### ISSUE TITLE
pub-sub Docker image Python 3.10 breaking change

### ISSUE THREAD

**Issue by mihaidraghici98** [GoogleCloudPlatform/kubernetes-engine-samples#224]
Hello!

There's an issue with `gcr.io/google-samples/pubsub-sample:v1` image.

It fails on startup due to MutableMaping not being found in collections library.
In Python3.10 there is a breaking change which removed collections.MutableMaping alias which poited to collections.abc.MutableMaping:

> Aliases to Abstract Base Classes in the collections module, like collections.Mapping alias to collections.abc.Mapping, are kept for one last release for backward compatibility. They will be removed from Python 3.10.
[What's new in Python3.9](https://docs.python.org/3/whatsnew/3.9.html)

A quick solution that I have found is changing the base image in the Dockerfile [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/718e09b69a1224e17930354d6e0eff4e18a5e67f/cloud-pubsub/Dockerfile#L1) to python:3.8-slim

**Comment by NimJay** [comment]
Hello @mihaidraghici98.
Thank you so much for reporting this issue and suggesting a solution. :)

@ckim328  
So sorry! 😅 
I misread and misunderstood the issue — I thought `docker build`-ing of the `pubsub-sample:v1` was broken. But now I understand that deployment of the image is broken. Your initial "p1" label was definitely correct. I was wrong when I suggested that this is a "p2".

I am currently reviewing #225.

**Comment by NimJay** [comment]
This issue is now fixed. See #225.
Thanks again, both of you! :)
