### ISSUE TITLE
Update to dockerfile images 

### ISSUE THREAD

**Issue by xtineskim** [GoogleCloudPlatform/kubernetes-engine-samples#267]
# Context
Renovate bot opened a PRs near the end of last year to update our dockerfile images (major bumps). To avoid ur renovate-bot  spam, we closed the PRs. This issue is to keep track of them so that we can (hopefully) edit our renovate-bot to not ignore them.

## Past PRs
- [ ] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/245
- [x] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/246
- [ ] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/247
- [ ] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/248
- [ ] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/252
- [ ] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/253
- [ ] https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/255

**Comment by mathieu-benoit** [comment]
For Whereami app with `python:3.10`: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/317
