### ISSUE TITLE
Bump PubSub

### ISSUE THREAD

**Issue by xtineskim** [GoogleCloudPlatform/kubernetes-engine-samples#284]
_Major_ bump in our dependency google-cloud-pubsub to v2 will require more work than what renovate bot PRs are showing. 
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/280

**Comment by minherz** [comment]
@bourgeoisor can you please to have a look whether we need to upgrade the pubsub version to 2.*

**Comment by bourgeoisor** [comment]
Yes it's using `v0.25` which is from 2017 (6 years old)
We should update to the latest, `v2.16`

https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/cloud-pubsub/requirements.txt

**Comment by bourgeoisor** [comment]
Reopening because of #574 (I reverted the changes in #572)

**Comment by minherz** [comment]
The code should be modified to use the handwritten methods as it is described in the [documentation][1].
The version 2.* of the library requires setting project ID as a part of the initialization process.
The project ID can be retrieved using one of the following methods:

* It can be provided explicitly via environment variable or configuration
* It can be read from metadata server assuming the code sample runs on GKE using `from from google.cloud import runtimeconfig`
* Retrieving quota project ID from authentication process (need to figure out how)

[1]: https://cloud.google.com/pubsub/docs/pull#python
