### ISSUE TITLE
GKE autopilot cluster unable to schedule

### ISSUE THREAD

**Issue by jingliangjl** [GoogleCloudPlatform/kubernetes-engine-samples#314]
We met an issue with GKE autopilot, and would like to ask a few questions about this issue.

Here are the details of our issue:
Our GKE autopilot cluster was working fine before, but since last week the deployment has been unable to deploy new versions and keeps saying "unable to schedule, insufficient cpu"
![image](https://user-images.githubusercontent.com/61960125/170613686-57b2bcbc-d2a4-412b-bf79-6a2b7d362295.png)

Here are the details of our cluster:
Mode: Autopilot
Release channel Rapid channel
Version 1.22.8-gke.200
Location type Regional
Region us-central1
Anthos Service Mesh Enabled
Workloads: Six deployments(three environments, each env includes one frontend app and one backend app, every deployment only has one pod), cert manager, asm-istio-ingressgateway.

Based on the above contexts, we have a few questions:
1) We are using Autopilot, and our application is not that complicated. The cluster autoscaler is reporting an error for scale-up, how can we see more detailed reasons or debug for why the pods are at risk of not being scheduled?
2) We found quota may be the solution through CLI suggestions, but quota usage in GKE Hub API is only 60%(limit is 15, 7 day peek usage is 9), because we have no other ideas to solve this problem, so we try to submit requests to see if it works. Currently, the quota limit is increased to 20, no error is reported, and our app can be successfully deployed. 
I would like to ask if the problem we encountered is really caused by insufficient quota?

Thank you

**Comment by ckim328** [comment]
hi @jingliangjl, 
I have a few questions:
- I see Anthos Service Mesh is enabled, just wondering how you set it up (any links to guides would be helpful)
- did you have the autopilot cluster with your application running, then you tried layering Anthos Service Mesh on top of it?
- are there any relevant logs that you can see from log monitoring in GCP?
Also feel free to dm me, I'd be happy to help you dig into this

**Comment by jingliangjl** [comment]
Hi @ckim328 ,

1. For setting up Anthos Service Mesh, our references are from:

  -   [Google cloud managed anthos service mesh doc](https://cloud.google.com/service-mesh/docs/managed/configure-managed-anthos-service-mesh)
  -   [Google cloud asmcli overview](https://cloud.google.com/service-mesh/docs/unified-install/asmcli-overview)
  -   [Github ASM istio-ingressgateway demo code](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/tree/main/samples/gateways/istio-ingressgateway)

Our command is: 
```
curl https://storage.googleapis.com/csm-artifacts/asm/asmcli_1.12 > asmcli
chmod +x asmcli
./asmcli install --use_managed_cni --managed --channel regular --cluster_location $CLUSTER_REGION \
            --cluster_name $CLUSTER_NAME --enable_all --enable_registration --fleet_id $PROJECT_ID  \
            --output_dir asm-files --project_id $PROJECT_ID --verbose
```

2. Our steps are:

  -   step 1: Create the autopilot cluster; 
  -   step 2: Install anthos service mesh;
  -   step 3: Deploy our app

3.  I'm afraid not. Did not see any relevant logs.

If you have more questions or need more information, please feel free to comment.

**Comment by ckim328** [comment]
hi @jingliangjl,
Thanks for the links/answers. 
Hmm from my first instinct, GKE autopilot shouldn't be unable to scale up - quota or not.
are there any restarts when running kubectl get pods on your namespace? Did the pods stop scaling up after applying ASM , or was this occur when a new version of you app was being rolled out? It may just be the autoscaler updating the pods

**Comment by ckim328** [comment]
Hi @jingliangjl! Sorry for the delay, I was following up around this.

Around May 10th, GKE is now requiring serial port logging, which seem to fit with the timeline of when your cluster started having issues. 
Could you check if you've enabled the `disableSerialPortLogging` constraint in your GCP project?
(here is a [resource for org policy constraints](https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints))
(here is a [guide on using constraints](https://cloud.google.com/resource-manager/docs/organization-policy/using-constraints))
(here is a [guild for enabling/disabling serial port logging](https://cloud.google.com/compute/docs/troubleshooting/viewing-serial-port-output#enable-stackdriver))

**Comment by jingliangjl** [comment]
Hi @ckim328 ,
No worries, thank you so much, and really appreciate your help.

Because I don't have the permission to modify policies at the organization level, the `disableSerialPortLogging` constraint I viewed in our project was **inherited**. 

So before requesting the permission I tried to disable `disableSerialPortLogging` constraint at the project level via the command `gcloud compute project-info add-metadata --metadata serial-port-logging-enable=true` and the console reported an error: **Constraint constraints/compute.disableSerialPortLogging violated for project**. 

This also shows that our organization level should have enabled the `disableSerialPortLogging` constraint, as mentioned in the documentation you provided([Link](https://cloud.google.com/compute/docs/troubleshooting/viewing-serial-port-output#setting_an_organization_policy))
<img width="910" alt="image" src="https://user-images.githubusercontent.com/61960125/171560922-2f848419-a52d-40c0-be5b-9b74676c4bf8.png">


So I would like to ask if we can just disable `disableSerialPortLogging` constraint and our GKE will be back to normal? 
Also can you help to explain why GKE requires serial port logging? 

Thanks!

**Comment by bourgeoisor** [comment]
That seems to be the case, yes. I would also look into _when_ the constraint was adding to your org (by asking the org owners) and see if it coincides with the auto-scaling issues.

The GKE team has let me know that serial port logging has more or less always been required for the well-working of GKE.

If you do get that constraint removed and the auto-scaling is still failing, do let us know and we'll look into it further.

**Comment by bourgeoisor** [comment]
I totally understand the concern. Serial port logging is leveraged to troubleshoot node issues (https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs#defaults), and with it disabled it becomes difficult or impractical to diagnose crashes or boot issues.

For GKE Autopilot, Google provide SLAs down to the Pod level describing uptime that needs to be respected (https://cloud.google.com/kubernetes-engine/sla) and requires serial port logging to be enabled to be able to meet those standards. Because of this, GKE Autopilot is not able to provision new nodes in orgs or projects with a `disableSerialPortLogging` constraint.

For GKE Standard, while serial port logging is not required, it impedes troubleshooting and diagnostics of node issues, and thus we highly recommend it to be enabled.

We're looking into updating the documentation to be more explicit about this; thank you for your understanding! In the meantime, let us know if you have any more questions or concerns!

**Comment by jingliangjl** [comment]
Thank you and Christine for all the help, really appreciate it.

I have no further questions, and I will close this issue.

**Comment by bourgeoisor** [comment]
@jingliangjl Hi! I wanted to check in to let you know that we're already working on these documentation and processes changes. Thank you for pointing this out to us. This page in particular has been updated already: https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints

> Disabling serial port logging can cause certain services that rely on it, such as GKE Autopilot, to not function correctly. Before you enforce this constraint, verify that the products in your project do not rely on serial port logging.
