### ISSUE TITLE
I'm getting a volume mount error for Cloud SQL set-up

### ISSUE THREAD

**Issue by EwanValentine** [GoogleCloudPlatform/kubernetes-engine-samples#33]
Hi there, I've followed [these instructions](https://cloud.google.com/sql/docs/postgres/connect-container-engine) step-by-step and have cross-references the configuration in this codebase, but I'm getting the following error when trying to start my container:

```
MountVolume.SetUp failed for volume "kubernetes.io/secret/2abd4716-bb10-11e7-82b8-42010a84010c-cloudsql-instance-credentials" (spec.Name: "cloudsql-instance-credentials") pod "2abd4716-bb10-11e7-82b8-42010a84010c" (UID: "2abd4716-bb10-11e7-82b8-42010a84010c") with: secrets "cloudsql-instance-credentials" not found
```

**Comment by AthenaShi** [comment]
From the error message, it seems like the instance credential secret was not created.

Please follow the steps in "2. Create a service account" and "5. Create your Secrets" and check if any error returned when create the cloudsql-instance-credentials secret.
