### ISSUE TITLE
Can't connect to application using external IP

### ISSUE THREAD

**Issue by ryanmcginnis** [GoogleCloudPlatform/kubernetes-engine-samples#36]
In following Kubernetes Engine's [quickstart](https://cloud.google.com/kubernetes-engine/docs/quickstart), I found that I'm not able to connect to the application using its external IP address.

Steps to reproduce:
1. `kubectl run hello-web --image=gcr.io/google-samples/hello-app:1.0 --port=8080`
2. `kubectl expose deployment hello-web --type="LoadBalancer"`
3. Attempt to visit the app's external IP addresse, gathered from `kubectl get service hello-web`
4. Observe that the site times out.

I'm not sure if this is an issue with how the application is written or if it's an issue with how its Service is configured. Also, I haven't tested from another environment, so I'd be interested to learn whether another user can reproduce.

**Comment by ahmetb** [comment]
@ryanmcginnis  I cannot reproduce this on my cluster. Here are some things that might've gone wrong:

1. Are you adding `:8080` port number to the external IP address?
2. You might have hit a quota in your GCP project. Can you send the output of `kubectl describe service hello-web`, this should show if the load balancer is created correctly or not.

**Comment by ryanmcginnis** [comment]
I am specifying the port. Here is the output of `kuebctl describe`:

```
Name:                     hello-web
Namespace:                default
Labels:                   run=hello-web
Annotations:              <none>
Selector:                 run=hello-web
Type:                     LoadBalancer
IP:                       10.63.242.155
LoadBalancer Ingress:     104.154.217.236
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30237/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  CreatingLoadBalancer  2m    service-controller  Creating load balancer
  Normal  CreatedLoadBalancer   1m    service-controller  Created load balancer
```

**Comment by ryanmcginnis** [comment]
I found the problem and I think it's interesting behavior:

```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  4s (x1378 over 6h)  default-scheduler  No nodes are available that match all of the following predicates:: PodToleratesNodeTaints (1).
```

I had a taint for this cluster's nodes. I would have expected to be warned in the CLI or to see in the UI that the Pods weren't being scheduled because of this. But it's fair that most users would probably remember setting a taint.

Thanks for your review!

**Comment by ahmetb** [comment]
> would have expected to be warned in the CLI or to see in the UI that the Pods weren't being scheduled because of this.

Scheduling in Kubernetes happens asynchronous of Pod creation. In this case, we actually create more indirection by deploying pods using Deployment controller. I suspect this is by design.
