### ISSUE TITLE
Hyperlinks broken in Cloud Shell code editor (Orion)

### ISSUE THREAD

**Issue by Deleplace** [GoogleCloudPlatform/kubernetes-engine-samples#38]
3f9c23dcc52ffa02a710487d6135b59b283abe76 had this unfortunate side effect (highlight by me) : 

![try-gke broken hyperlinks](https://user-images.githubusercontent.com/13508141/33986683-9f2f0d78-e0be-11e7-885a-a30cb0355bb1.png)

I guess this happens because Cloud Shell code editor is not "as powerful" as Github when interpreting markdown.

But this screen is what the user sees when following some "Try GKE" public links (e.g. at bottom of https://cloud.google.com/kubernetes-engine/kubernetes-comic/ ), so I regard it as a bug.

**Comment by ahmetb** [comment]
@Deleplace yes we're aware of this. @synemitchell
