### ISSUE TITLE
Invalid JSON File (credentials.json)

### ISSUE THREAD

**Issue by novacp** [GoogleCloudPlatform/kubernetes-engine-samples#40]
I've been following your instructions, but keep getting the following error when applying the deployment for the cloudsql proxy:

"2017/12/18 20:56:29 invalid json file "/secrets/cloudsql/credentials.json": invalid character '\n' in string literal"
-> created the secret with JSON format as you describe.

Is this a common issue? Couldn't find anything about it...

**Comment by ahmetb** [comment]
Can you mount the secret in another container and `kubectl exec` into the container, then `cat` it?

My suspicion is that there's actually a problem with your JSON file. (Did you open your key file and was it indeed JSON? Can you pass it to a JSON parser to verify, either online or command like such as `cat key.json | jq '.'`?)

**Comment by novacp** [comment]
Hi Ahmet,
indeed, there was a problem within the json credentials file - BUT the problem was already in it when I downloaded it from within GCloud service account.. there were some "\n" charakters within it, when I used an online json parser, took the outcome (as how it is being interpreted) and replaced the credentials.json content with the new content, the problem is gone. Now I just keep getting the error "MySQL server has gone away", might this be related? Does the error now indicate a permission problem?

**Comment by ahmetb** [comment]
@novacp can you please share the screenshot of the key file here by redacting the actual secret string? I'd be really surprised if your secret is actually downloaded as malformed.

**Comment by novacp** [comment]
`{
  "type": "service_account",
  "project_id": "removed",
  "private_key_id": "removed",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBA................................................Dn9Cb\ndjyiiOqGaDibEgBVAfBjX...............................................Mz7w\ncDQJ/tmkoKSG5mDw3+b0.................................................NsSoDXF\n9I7O6D1bXQ+JVw+n913fp+goFt3y76bt1PjhrGuZ487k1FLSG5LxzEtk86OPUqzG\nBlJNyqMcTeUXTZ.....................................a45CJ83dUise\nGn//RDKBRMCKi6I...............................fITnLqNEfbQ\nW69+fas5AgMBAAECggEACpnEO0kyjNaEXe7u7lwIGAuSbxOoQtvIA+XRhcIeDN+l\nLJCSHE/mMQ7LJg1/9NADHqAAO/tjJb......................................92fG/v\n5r/CnohMCYkNii8BiY1u9loo11JDHsYfEpw1sO4sp9FNzjJ/CSbu8RTl8f7JoJvb\nD+FPsG/0pH0mlzN3+88yrAlU5N1JTTUBiBGGuIhPJ5L7ypLfF9VpiLg7KEuR5j+U\nBLUnhRzr5Uiy70Qi2PsSEON5vw5hP6jvAibcO2CnWbs/07UMxb24dn8aug3U/346\nHV+U9//ladrogZPC2YWItycZAQE............................................embQb\nCPVkCp73k0jE2u5b5/acsidCPlTmtrbyV/KIes146C9YBPurpWPf2TRR3QSIzDXi\nwY5vui.......................................pd2FBx\nqQIDvQitqAWfT9D+5yyY..............................................KuJ3Wao+lpy\nnZg5Viz6s5JjQwbXFVL+.......................................XYRc/\nd3IMdIcrIHw/1wNK+Bbjy8ePMTfKhfL5vhoJVRSTMs8pzzzWXb6mnkpo2shOsRW3\n6ZRZVTjuOQKBgQC+Net3tTekDWfaE+1/vg1Skq5o+QEMvKgBfZxXC0xi7TuV3+/J\nNpnk22dAly........................Rm0AE1QVZ/YP\n/HmT22xiamP7PMLjb08ZaNZJii41Ka3aSWKYsQZT2yI8jukh/m23H7V3AQKBgB/z\nkSXDPTNnAw+2S7FXHv6ePxV5EQzJw9/DyLCkUd5tDmhEObwB9Z43JvaGpLGPn/Go\nUHw2mz2cpv.................................................................UdHPVB1F/CZLyE4\ngwIrU3ebEfwm5h2IMxKHEnFlUdkGDeu4vbzuHoZBAoGAGzZA9wozWjaqk5BVOs4/\n/DklSzV8ciDVPV9hq/uaur4JQkhDVYuCp2hckgT1rGhU3N4nOEZy1Y0Xs6wptHlS\n6equjiMhmCvcSmCZ7DF4aZz6JMcok5Qm1dGNFlBF0GZ7/jHmcsWL70vySrZHxUQz\nxOR+rSBPU/ZsmapHOgh4f0c=\n-----END PRIVATE KEY-----\n",
  "client_email": "removed",
  "client_id": "removed",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "removed"
}
`

Thats the file I get back from GCloud - you see "\n"s? These caused the error.. btw. I already deleted the secret.

**Comment by ahmetb** [comment]
The reason I asked you to share feedback is because github will eat your new line breaks. 

So I'm editing your paste now to switch to 3-backticks syntax.

**Comment by ahmetb** [comment]
@novacp your Service Account key seems normal. `\n` occurrences in `"private_key"` field are expected. It's still a single-line string as far as JSON formatting is concerned. 

Since you said this I am concerned:

> when I used an online json parser, took the outcome (as how it is being interpreted) and replaced the credentials.json content with the new content, the problem is gone.

The JSON you pasted above seems parsable by `jq`, a command-line JSON parser.

Can you please send me a revoked key file that's causing you a problem (my email is ahmetb at google dot com)? I'd like to see how reformatting it with an online parser could fix it.

**Comment by novacp** [comment]
@ahmetb mail sent, topic is the URL of this thread.

**Comment by ahmetb** [comment]
@novacp the service account you sent seems perfectly okay, and the json parser you're using is actually eating the newlines and replacing them with space (not okay).

This tampering is giving you the error:

> private key should be a PEM or plain PKSC1 or PKCS8; pars e error: asn1: structure error: tags don't match

So there's probably a problem with cloudsql proxy. Which version of the cloudsql-proxy image are you using? 

My plan is to re-execute tutorial at https://cloud-dot-devsite.googleplex.com/sql/docs/mysql/connect-kubernetes-engine due to your report. If you want to run through it and actually use wordpress/mysql example and see if it works, that would be great.

**Comment by novacp** [comment]
I will re-execute the tutorial now and send you an email again with files as attachment.

**Comment by novacp** [comment]
I setup a new test env (removing all docker containers, pods, deployments, keys etc.) and now the error does not occure again.. I can now connect to CloudSQL using cloudsql-proxy v1.11.

**Comment by ahmetb** [comment]
Good to hear! 👍
