### ISSUE TITLE
The last commit breaks redis-follower startup script

### ISSUE THREAD

**Issue by suulperi** [GoogleCloudPlatform/kubernetes-engine-samples#441]
Last modification (Google's Copyrights comments) of redis-follower startup script [guestbook/redis-follower/run.sh] breaks it. Commit fb608f7fe47ff9213caefab7851ac24a699f5bee

The first row of run.sh should be #!/bin/bash but it is after copyrights and because of it script is using dash instead of bash for running it and it won't work properly. It's breaking if else statement logic.
```
/run.sh
/run.sh: 19: /run.sh: [[: not found
```

**Comment by NimJay** [comment]
Thanks for reporting this issue, @suulperi! :)
It will be resolved by https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/442 — once I get an approval from my team.
