### ISSUE TITLE
missing --zone in "gcloud container clusters create" command

### ISSUE THREAD

**Issue by DanRoscigno** [GoogleCloudPlatform/kubernetes-engine-samples#51]
When creating the cluster for the persistent storage example the command in the doc is:
gcloud container clusters create persistent-disk-tutorial --num-nodes=3

I received an error telling me that I had to specify a zone, so I ran this (successfully):
gcloud container clusters create persistent-disk-tutorial --num-nodes=3 --zone=us-central1-a

Have a good day, and thanks for the examples!

**Comment by DanRoscigno** [comment]
Sorry, I found my issue, my fault, I had not set the zone as an env var.

**Comment by ahmetb** [comment]
You can also set it as a default config, as covered in our tutorial: https://cloud.google.com/kubernetes-engine/docs/tutorials/persistent-disk

    gcloud config set compute/zone us-central1-b
