### ISSUE TITLE
Revise samples for autopilot networking tutorial

### ISSUE THREAD

**Issue by melissakendall** [GoogleCloudPlatform/kubernetes-engine-samples#571]
Hello,

This is a request to revise /kubernetes-engine-samples/tree/main/autopilot/basic-networking-bank-of-anthos as follows:
- Split ingress.yaml into seperate manifests by KIND, which helps with formatting the tutorial that will use those manifests
- Format variable names as caps (i.e. CERTIFICATE_NAME) to prepare for variable insertion in the tutorial that will use this variables and remove "bank-of-anthos" for each name, which is difficult for maintenance and logical understanding of each variable (if everything is named "bank-of-anthos", its hard to track names through the tutorial)
- Insert Terraform manifests so they are not hard-coded in the tutorial that will use this folder (optional, will discuss with team)

I request permission to create a branch to make these changes.

Thank youm
-Melissa

**Comment by minherz** [comment]
Hi @melissakendall ,
Thank you for your input. We agree that clarity of the source code is important. Feel free to [fork this repo][1] and submit the changes that you see fit via a [pull request][2]. You do not need special permissions to do it. If you contribute to this repo first time, please familiarize with the [CONTRIBUTING][3] guide.

[1]: https://docs.github.com/en/get-started/quickstart/fork-a-repo
[2]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
[3]: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/1cf2f30520e0615715fc07f77c9a1548dc07c00d/CONTRIBUTING.md

**Comment by bourgeoisor** [comment]
Alternatively to splitting the manifest, you can instead use region tags surrounding the lines that you want to integrate in the docs (example: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/quickstart/deployment.yaml#L16)

**Comment by bourgeoisor** [comment]
@melissakendall if you put "Fixes #123" with the issue number in the description of a PR, it'll tie them together and closing the PR will also close the issue -- I will reopen and do that now!
