### ISSUE TITLE
AttributeError: module 'google.cloud.pubsub_v1' has no attribute 'Subscription'

### ISSUE THREAD

**Issue by gartemiev** [GoogleCloudPlatform/kubernetes-engine-samples#574]
When I run this application in GKE I get: 
`
$ kubectl logs -l app=pubsub

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main()
  File "main.py", line 20, in main
    request = pubsub_v1.Subscription(
AttributeError: module 'google.cloud.pubsub_v1' has no attribute 'Subscription'
`

**Comment by bourgeoisor** [comment]
Hello @gartemiev! Could you be more specific? For example:
- Which sample application are you referring to?
- Did you follow the sample using a specific tutorial? If so, which one?
- How did you run the sample? Any other relevant info?

**Comment by eoincarroll** [comment]
I am getting the same issue in this guide (https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform) just after you apply the first yaml in "Deploying Pub/Sub subscriber application"

**Comment by bourgeoisor** [comment]
Oh I see. Seems like this may be due by: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/572
cc: @minherz FYI

**Comment by bourgeoisor** [comment]
I reverted the changes in #572 and reopened #284
Samples should work as they were before this changes (you will have to `git pull` to get the latest changes, but let me know if that's not the case

**Comment by minherz** [comment]
Thank you, @eoincarroll for letting us known. The tutorial that you reference uses the same codebase as one that cause the error. We will refactor the code so it will use the last version of the pubsub client library correctly. Please, track #284 for more updates.
