### ISSUE TITLE
cloud-sql-postgres ServiceClass support

### ISSUE THREAD

**Issue by addisonbair** [GoogleCloudPlatform/kubernetes-engine-samples#65]
Is there any prioritization for including Cloud SQL Postgres as part of the default service classes? If not, I am curious what would be required to add Postgres support. The CloudFoundry project has had Postgres support for quite a while now, but it is not clear from documentation on how to build your own service broker/catalog from source. Any suggestions or tips would be greatly appreciated, thank you!

**Comment by ahmetb** [comment]
Hi, this repository is not the issue tracker for products. Please open an issue at https://issuetracker.google.com/savedsearches/559755

**Comment by ahmetb** [comment]
Sorry that link goes to GCE. For Kubernetes Engine, use the issue tracker: https://issuetracker.google.com/savedsearches/559746 or create an issue: https://issuetracker.google.com/issues/new?component=187077&template=0
