### ISSUE TITLE
transfer-datasets.sh still references deleted variables.sh file

### ISSUE THREAD

**Issue by natea123** [GoogleCloudPlatform/kubernetes-engine-samples#678]
Following step 3 of [batch ml GKE tutorial](https://cloud.google.com/kubernetes-engine/docs/tutorials/batch-ml-workload#set_up_a_redis_job_queue):

```
sh scripts/transfer-datasets.sh
scripts/transfer-datasets.sh: line 16: scripts/variables.sh: No such file or directory
```
#510 deleted the "obsolete" script however transfer-datasets.sh still sources from it. No clear workaround as deleting the source command from the script errors out as well.

**Comment by minherz** [comment]
@natea123 can you please have a look and address the feedback comments in #679?
