### ISSUE TITLE
[cloudsql] Error 403: The client is not authorized to make this request., notAuthorized with Project > Editor role

### ISSUE THREAD

**Issue by chirangaalwis** [GoogleCloudPlatform/kubernetes-engine-samples#68]
I've attempting to perform a sample WordPress deployment using Google Cloud SQL by following [1].

The original documentation I've followed is [2]. The doc states that even if I don't possess **Cloud SQL > Cloud SQL Client** role, alternatively I could use the **Editor** role to perform this deployment [3]. I assume the **Editor** role when checked in IAM.

Yet, I am experiencing the following error which has already been pointed out previously in [4].

Any help or suggestions are appreciated.

```
2018/05/12 14:45:34 couldn't connect to "<connectionName>": ensure that the account has access to "<connectionName>" (and make sure there's no typo in that name). Error during createEphemeral for <connectionName>: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```
[1]: [Using Google Cloud SQL from a WordPress Deployment
](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/cloudsql)
[2]: [Connecting from Kubernetes Engine](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)
[3]: [Create a service account](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#2_create_a_service_account)
[4]: [[cloudsql] Error 403: The client is not authorized to make this request., notAuthorized](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/10)

**Comment by ahmetb** [comment]
@chirangaalwis it might be good to paste your Kubernetes YAML manifest files. I am able to follow the tutorial at [2] and succeed just fine. Also you should not be needing "Editor" role (I filed a bug internally to remove this statement).

**Comment by chirangaalwis** [comment]
@ahmetb thanks for the quick response.

The truth is I have simply deployed the Kubernetes manifest file provided at [1].

It seems I don't have permissions to set the **Cloud SQL > Cloud SQL Client** role
![152615830429070236](https://user-images.githubusercontent.com/9444555/39961359-219ecb1e-5652-11e8-898a-c89c362040a2.png).

Yet as I have mentioned earlier, I assume an **Editor** role and based on the documentation [2] I expected to use this role alternatively, to perform the task. But as you have suggested since, the **Editor** role has nothing to do with it, I assume we **must** assume **Cloud SQL > Cloud SQL Client** role to perform the task, successfully.

Please correct me if I am wrong.

[1]: [Using Google Cloud SQL from a WordPress Deployment](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/cloudsql)
[2]: [Connecting from Kubernetes Engine](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)

**Comment by robsonpeixoto** [comment]
Create another service account after Enable the Cloud SQL API

**Comment by JensMadsen** [comment]
@robsonpeixoto solved my problem!! Perhaps this should be added to the docs?

**Comment by kelvinrferreira** [comment]
There is a better solution that doesn't require a new service account creation.

> Here's what worked for me -- I didn't need to create a service account:
gcloud auth application-default login
For some reason it changes how the login is handled.

Source from @sventech https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/10#issuecomment-380945047
