### ISSUE TITLE
SIGTERM not handled by direct-to-sd custom metrics example

### ISSUE THREAD

**Issue by alissonperez** [GoogleCloudPlatform/kubernetes-engine-samples#69]
Hi Guys/Girls! =)

I was trying to use the `custom-metrics-autoscaling/direct-to-sd/` example in my cluster but I notice that it is not handling SIGTERM (and other signals...) when we terminate a pod. I made this change in a fork and now it's seems working properly: https://github.com/alissonperez/kubernetes-engine-samples/commit/ee577dbdbbdee5f7a4a1083feb6e97651403f4f5

Please, take a look, if you agree I can open a PR with these changes!

Thank you!

**Comment by ahmetb** [comment]
Please feel free to send a PR. The changes look good.
