### ISSUE TITLE
CloudVolume - example missing

### ISSUE THREAD

**Issue by arindam-b** [GoogleCloudPlatform/kubernetes-engine-samples#746]
Hi there,

I am using GCP Cloud volumes in GKE for my project for more than 1 year and I find it missing in this repository.

May I contribute the source code to this repository?

**Comment by bourgeoisor** [comment]
Hi @arindam-b! Thank you for your enthusiasm, but this repo is strictly used for hosting samples that appear in official GKE tutorials (https://cloud.google.com/kubernetes-engine/docs/concepts/kubernetes-engine-overview)

Your feedback on the low #s of samples for volumes with GKE is noted!
