### ISSUE TITLE
Mention --ip_address_types Cloud SQL proxy flag

### ISSUE THREAD

**Issue by hfwang** [GoogleCloudPlatform/kubernetes-engine-samples#80]
@kurtisvg should we mention the --ip_address_types flag in the deployment yamls:

https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/cloudsql/postgres_deployment.yaml
https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/cloudsql/mysql_wordpress_deployment.yaml

Perhaps in the command args array, add something like:
```
# Uncomment below to force the pod to use the private IP address of the Cloud SQL instance.
# The instance must have a private IP on the same network and in the same region.
# "-ip_address_types=PRIVATE",
```

**Comment by kurtisvg** [comment]
Update version as well
