### ISSUE TITLE
[cloudsql] need to set 0.0.0.0 address on container command 

### ISSUE THREAD

**Issue by bokuo-okubo** [GoogleCloudPlatform/kubernetes-engine-samples#84]
[This page](https://cloud.google.com/sql/docs/mysql/connect-docker#connect-client) says like below.

>  The "0.0.0.0" in the instances parameter is required to make the port accessible from outside of the Docker container.

https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/cloudsql/mysql_wordpress_deployment.yaml#L45

The line should be `"-instances=<INSTANCE_CONNECTION_NAME>=tcp:0.0.0.0:3306"`

**Comment by ahmetb** [comment]
That’s only the case of you’re exposing proxy port to outside the Pod I believe.

If you’re using a sidecar container (which is more secure and recommended), you should not use 0.0.0.0 as it will accept connections from outside the Pod.
