### ISSUE TITLE
question: GKE VPA recommender proto generation

### ISSUE THREAD

**Issue by matdtr** [GoogleCloudPlatform/kubernetes-engine-samples#894]
Hi, 

How has been generated the file [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/fcc11659fd2c0ebdb4c252a8ce0c3ea0dc8556de/gke-vpa-recommendations/metrics-exporter/bigquery_schema_pb2.py) starting from the protoc definition?

**Comment by bourgeoisor** [comment]
@aburhan can you answer that one? Is that something we should document?

**Comment by minherz** [comment]
Hello @matdtr you can use the standard compiler for Python (`protoc`) as in the following command:

```bash
protoc --python_out=. bigquery_schema.proto
```

You can review [Protocol Buffers Documentation][1] for more information.

[1]: https://protobuf.dev/getting-started/pythontutorial/
