### ISSUE TITLE
Issue while connecting to mysql instance from application deployed on azure cluster

### ISSUE THREAD

**Issue by mart3051** [GoogleCloudPlatform/kubernetes-engine-samples#91]
I tried to follow the instruction with the sample example cloudsql-mysql.
It works perfectly if the cluster is a GCP cluster and the service broker is gcp- broker.
However if I try the same on an azure cluster following is the issue faced.

When I was trying the step post deployment to curl the URL , it gave time out error.
Then I tried 
`kubectl get pods -n cloud-mysql`

which gave 
`NAME                         READY   STATUS             RESTARTS   AGE
musicians-586557cdf5-ksv9z   1/2     CrashLoopBackOff   3          8m26s`
Logs give the below details.
`kubectl logs musicians-586557cdf5-ksv9z -n cloud-mysql --all-containers=true`

Output
`2019/03/19 10:35:37 DB_PASSWORD environment variable unspecified or ''
[mysql] 2019/03/19 10:35:37 packets.go:36: unexpected EOF
[mysql] 2019/03/19 10:35:37 packets.go:36: unexpected EOF
[mysql] 2019/03/19 10:35:37 packets.go:36: unexpected EOF
2019/03/19 10:35:37 Failed to create a database: driver: bad connection
2019/03/19 09:54:10 using credential file for authentication; email=cloudsql-user-service-account@kubeservicebroker27.iam.gserviceaccount.com
2019/03/19 09:54:10 Listening on 127.0.0.1:3306 for kubeservicebroker27:us-central1:musicians-20326
2019/03/19 09:54:10 Ready for new connections
2019/03/19 09:59:30 New connection for "kubeservicebroker27:us-central1:musicians-20326"
2019/03/19 09:59:31 couldn't connect to "kubeservicebroker27:us-central1:musicians-20326": ensure that the account has access to "kubeservicebroker27:us-central1:musicians-20326" (and make sure there's no typo in that name). Error during createEphemeral for kubeservicebroker27:us-central1:musicians-20326: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
2019/03/19 09:59:31 New connection for "kubeservicebroker27:us-central1:musicians-20326"
2019/03/19 09:59:31 Throttling refreshCfg(kubeservicebroker27:us-central1:musicians-20326): it was only called 713.896µs ago
2019/03/19 09:59:31 couldn't connect to "kubeservicebroker27:us-central1:musicians-20326": ensure that the account has access to "kubeservicebroker27:us-central1:musicians-20326" (and make sure there's no typo in that name). Error during createEphemeral for kubeservicebroker27:us-central1:musicians-20326: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
`

Can somebody please help what am I missing?

**Comment by Niraj-Fonseka** [comment]
+ looking for the answer for this as well

**Comment by mart3051** [comment]
I figured out the below works 
Must have 
gcloud auth application-default login  before sc install on .
However the project has a tendency to go in a state where it starts giving error post running for a few minutes.
Following helped me:
Recreate the service account(with same email id and CloudSQL.Client role) from gcloud console and restart the pods. If issue is not resolved and the below issue is encountered.
![image](https://user-images.githubusercontent.com/20171052/55554237-eaf3b480-56ff-11e9-85b0-4af303835066.png)
Edit the deployment.yaml by copying the password updated on gcp console for root user and redploy.
That might give no database selected
to solve that restart the pods.

If nothing works delete the project from gcp and start again and this time make sure
gcloud auth application-default login   is the first command you trigger. however have no clue of th ereasons of failure
