### ISSUE TITLE
[cloudsql] MountVolume.SetUp failed for volume "cloudsql-instance-credentials"

### ISSUE THREAD

**Issue by plexcellmedia** [GoogleCloudPlatform/kubernetes-engine-samples#93]
I'm getting this error when deploying using Helm.

`MountVolume.SetUp failed for volume "cloudsql-instance-credentials" : secrets "cloudsql-instance-credentials" not found`

I have created service account and db credentials and havent faced any errors.

```
kubectl get secrets
NAME                            TYPE                                  DATA      AGE
cloudsql-db-credentials         Opaque                                2         25m
cloudsql-instance-credentials   Opaque                                1         29m
```

My cloudsql deployment is exactly same as in examples.

**Comment by kurtisvg** [comment]
@plexcellmedia Are you still having trouble with this? I'm not able to replicate.

Can you verify that you haven't misspelled `cloudsql-instance-credentials` in the yaml?

**Comment by plexcellmedia** [comment]
@kurtisvg I got issue resolved, forgot to close this issue.

**Comment by kurtisvg** [comment]
No worries, thanks for following up.

**Comment by samarchowdhury** [comment]
> @kurtisvg I got issue resolved, forgot to close this issue.

Can you please suggest what you did to resolve the issue? I am getting the exact same issue.

**Comment by klaaz0r** [comment]
@kurtisvg Do you mind sharing your solution?

**Comment by kurtisvg** [comment]
@klaaz0r I'm not the OP, but the problem was almost certainly a configuration issue. Make sure you have created the secrets it's asking for and that everything is spelled correctly.

**Comment by klaaz0r** [comment]
Woops, sorry @kurtisvg  tagged the wrong person.

the solution can be found here: https://codelabs.developers.google.com/codelabs/cloud-postgresql-gke-memegen/#7

You need to do the following: create a secret with credentials 
```
kubectl create secret generic cloudsql-instance-credentials \
--from-file=credentials.json=../credentials.json
```
and a secret with the database credentials

```
kubectl create secret generic cloudsql-db-credentials \
    --from-literal=username=[DB_USER] \
    --from-literal=password=[DB_PASS] \
    --from-literal=dbname=[DB_NAME]
```

By following this https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine tutorial I got a little confused but if you follow these step you are set to go!
